CAJA = '$'
PARED = '#'
VACIO = ' '
JUGADOR = '@'
OBJETIVO = '.'
OBJETIVO_Y_CAJA = '*'
OBJETIVO_Y_JUGADOR = '+'

GRILLA = 0
NIVEL = 1
MOVIMIENTOS_DESHACER = 2
MOVIMIENTOS_REHACER = 3
MOVIMIENTOS_PISTAS = 4

SOLUCION_ENCONTRADA = 0
SOLUCIONES = 1

SALIR = 'SALIR'
REINICIAR = 'REINICIAR' 
REHACER = 'REHACER'
DESHACER = 'DESHACER'
PISTAS = 'PISTAS'

LEVEL_HEADER = 'Level'

OESTE = (-1, 0)
ESTE = (1, 0)
NORTE = (0, -1)
SUR = (0, 1)
DIRECCIONES = { 'OESTE': OESTE, 'ESTE': ESTE, 'NORTE': NORTE, 'SUR': SUR }
LISTA_DIRECCIONES = [OESTE, ESTE, NORTE, SUR]